### ISSUE TITLE
Request: Use NATO Target Location Error Categories in NATO Lowdown calls

### ISSUE THREAD

**Issue by phoenixegmh** [uriba107/DCS-Hound#1]
Primarily designed for CAS, but Target Location Error Categories put a category number against a Circular Error reference.

Reference JP 3-09.3 Page III-35

**Comment by uriba107** [comment]
I can try, but from my testings 90% of the time accuracy errors will be in CAT V or CAT VI.
But I'll definitely dig in some more in NATO docs for better bravety in future versions

**Comment by uriba107** [comment]
This type of accuracy rating is not suitable for ELINT due to the much larger error in positional accuracy. Hound v0.2 will include some changes to the LOWDOWN syntax, however this accuracy rating will not be used.

Thank you for suggesting this!
