### ISSUE TITLE
Script error in getRadarDetectionRange

### ISSUE THREAD

**Issue by Toumal** [uriba107/DCS-Hound#22]
Hi,
I'm getting the following error in the latest v0.2.0:

2022-01-04 11:06:34.848 ERROR   SCRIPTING: Mission script error: [string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis000038AD.lua"]:1291: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: ?
	[C]: in function 'pairs'
	[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis000038AD.lua"]:1291: in function 'getRadarDetectionRange'
	[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis000038AD.lua"]:2251: in function 'New'
	[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis000038AD.lua"]:3480: in function 'addContact'
	[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis000038AD.lua"]:3502: in function 'getContact'
	[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis000038AD.lua"]:3654: in function 'Sniff'
	[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis000038AD.lua"]:5193: in function <[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis000038AD.lua"]:5187>
2

The error occurs on the first "for" line in the following function:

    function HoundUtils.getRadarDetectionRange(DCS_Unit)
        local detectionRange = 0
        local unit_sensors = DCS_Unit:getSensors()
        if not unit_sensors then return end
        for _,radar in pairs(unit_sensors[Unit.SensorType.RADAR]) do
            for _,aspects in pairs(radar["detectionDistanceAir"]) do
                for _,range in pairs(aspects) do
                    detectionRange = l_math.max(detectionRange,range)
                end
            end
        end
        return detectionRange
    end

Note: This error has been present in the previous 0.1.x versions too.

**Comment by uriba107** [comment]
thanks for the report. I'll have a look.
do you have any idea which unit has triggered it?

meanwhile you can try adding a line and see if that would fix it. 
between the `if not` and `for _,radar` add the line
`if not setContains(unit_sensors,Unit.SensorType.RADAR) then return end`

I will test it soon and add to the next patch, but you can try it now and verify.

**Comment by Toumal** [comment]
Thanks for the super fast reply! Yep that did indeed help. Unfortunately I have no idea which unit caused this, I added this to our existing and rather large dynamic mission. Again, thanks!

**Comment by uriba107** [comment]
I'm keeping open until the fix has been pushed.
