### ISSUE TITLE
self:getTtsData() sometimes returns nil after destruction of SAM unit.

### ISSUE THREAD

**Issue by Toumal** [uriba107/DCS-Hound#23]
Another nil value error, returned from self:getTtsData(). Not sure if I'm the only one who gets this, because I don't do any scripted destruction or removal of units.

    function HoundContact:generateDeathReport(isTTS,sectorName)
        local msg = self:getName() .. " has been destroyed"
        if sectorName then
            msg = msg .. " in " .. sectorName
        else
            local GridPos,BePos
            if isTTS then
                GridPos,BePos = self:getTtsData(true,1)
                msg = msg .. ", bullseye " .. BePos .. ", grid ".. GridPos
            else
                GridPos,BePos = self:getTextData(true,1)
                msg = msg .. " BE: " .. BePos .. " (grid ".. GridPos ..")"
            end
        end
        return msg .. "."
    end

2022-01-04 18:36:10.918 ERROR   SCRIPTING: Mission script error: [string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis00005471.lua"]:2917: attempt to concatenate local 'GridPos' (a nil value)
stack traceback:
	[C]: ?
	[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis00005471.lua"]:2917: in function 'generateDeathReport'
	[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis00005471.lua"]:4364: in function 'notifyDeadEmitter'
	[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis00005471.lua"]:5336: in function 'onHoundEvent'
	[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis00005471.lua"]:2088: in function 'onHoundEvent'
	[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis00005471.lua"]:2101: in function 'publishEvent'
	[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis00005471.lua"]:3511: in function 'removeContact'
	[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis00005471.lua"]:3689: in function 'Process'
	[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis00005471.lua"]:5199: in function <[string "C:\Users\USER\AppData\Local\Temp\DCS.openbeta_server\/~mis00005471.lua"]:5188>

Cheers!

**Comment by uriba107** [comment]
Thanks.
It's an odd one. Is it on a pre-briefed contact or just some random target?

Can you provide some info on when it happens? I need to try and replicate it somehow.

**Comment by Toumal** [comment]
No that's a random target. Unfortunately I have no idea which one it was.
I can upload the mission here, maybe that helps.
[Caucasus_Dynamic_Conflict_v1.5.zip](https://github.com/uriba107/DCS-Hound/files/7809846/Caucasus_Dynamic_Conflict_v1.5.zip)

**Comment by uriba107** [comment]
Thanks! Much appreciated.
