### ISSUE TITLE
E-2D is being reported as an E-2C, so Hound doesn't use it 

### ISSUE THREAD

**Issue by delenda-delenda** [uriba107/DCS-Hound#27]
E-2Ds aren't working with Hound as something (I suspect DCS) is reporting the unit type as being E-2C instead. Duplicating the E-2D entry in the Platform Unit list and changing the name to E-2C is a workaround for the issue.

DCS version DCS/2.7.9.18080
HOUND version 0.2.1

**Comment by uriba107** [comment]
Thank you for reporting.
I'll push a Hotfix as soon as I can.
