### ISSUE TITLE
Error in local grpMenu on some events (v0.2.2) 

### ISSUE THREAD

**Issue by cammeltech** [uriba107/DCS-Hound#36]
Got this in the log files after the following events:

- event:type=crash,t=5101.702,initiatorPilotName=Tapas 2-2 [TM] Jaggerman,initiatorMissionID=3218,
- event:type=crash,t=9675.724,initiatorPilotName=Tapas 2-4 | [TM] Cammel,initiatorMissionID=2866,
- event:type=engine shutdown,initiatorPilotName=[TM] Hornet-3-3 | Lazy,place=Shiraz Intl,t=10607.7,placeDisplayName=Shiraz Intl,initiatorMissionID=2881,
- event:type=relinquished,initiatorPilotName=PLAYER,target=,t=11478.629,targetMissionID=_16778756,
- NET: accepting connection from 89.********:59880
- Changeslot

```
2022-04-10 17:19:19.109 ERROR   SCRIPTING: Mission script error: [string "D:\git\DCS-Hound\include\HoundElint.lua"]:5061: attempt to index local 'grpMenu' (a nil value)
stack traceback:
	[C]: ?
	[string "D:\git\DCS-Hound\include\HoundElint.lua"]:5061: in function 'populateRadioMenu'
	[string "D:\git\DCS-Hound\include\HoundElint.lua"]:6056: in function 'populateRadioMenu'
	[string "D:\git\DCS-Hound\include\HoundElint.lua"]:6030: in function <[string "D:\git\DCS-Hound\include\HoundElint.lua"]:5993>
2022-04-10 17:19:25.981 INFO    Scripting: event:type=engine shutdown,place=Kerman,t=4621.841,placeDisplayName=Kerman,initiatorMissionID=1000065,
2022-04-10 17:19:35.117 ERROR   SCRIPTING: Mission script error: [string "D:\git\DCS-Hound\include\HoundElint.lua"]:5061: attempt to index local 'grpMenu' (a nil value)
stack traceback:
	[C]: ?
	[string "D:\git\DCS-Hound\include\HoundElint.lua"]:5061: in function 'populateRadioMenu'
	[string "D:\git\DCS-Hound\include\HoundElint.lua"]:6056: in function 'populateRadioMenu'
	[string "D:\git\DCS-Hound\include\HoundElint.lua"]:6192: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>
```

**Comment by uriba107** [comment]
thanks for the report. I'll have a look.
temporary fix for now that would probabaly do the trick is changing line 5058
(```if not grpMenuDone[grpId] then```)
to
```if not grpMenuDone[grpId] and grpMenu ~= nil then```
that will just ignore the edge case that caused the fail. a better fix (or at least an effort for a better one) will be in 0.2.3 (I'll try and push this into the dev branch later today)
