### ISSUE TITLE
Error in toPhonetic

### ISSUE THREAD

**Issue by cammeltech** [uriba107/DCS-Hound#38]
I'm not sure what triggers this error.

2022-04-15 15:55:58.210 ERROR   SCRIPTING: [string "D:\git\DCS-Hound\include\HoundElint.lua"]:1832: attempt to concatenate field '?' (a nil value)
stack traceback:
	[C]: ?
	[string "D:\git\DCS-Hound\include\HoundElint.lua"]:1832: in function 'toPhonetic'
	[string "D:\git\DCS-Hound\include\HoundElint.lua"]:3578: in function 'getTtsData'
	[string "D:\git\DCS-Hound\include\HoundElint.lua"]:3619: in function 'generateTtsReport'
	[string "D:\git\DCS-Hound\include\HoundElint.lua"]:5284: in function <[string "D:\git\DCS-Hound\include\HoundElint.lua"]:5269>

**Comment by uriba107** [comment]
Thanks.
I'll try and replicate.
I've seen this maybe once before. I'll try to add some more safeguards there.
