### ISSUE TITLE
Would be cool to have a return value in HoundElint:addPlatform

### ISSUE THREAD

**Issue by davidp57** [uriba107/DCS-Hound#4]
like `return canidate`
btw lots of typos in the variable names here (even if syntaxically correct)

**Comment by davidp57** [comment]
Btw this is what a *canidate* could be : 
https://tenor.com/view/date-night-dog-spaghetti-lady-and-the-tramp-kiss-gif-15556098

**Comment by uriba107** [comment]
yup pretty much!

function will return True if platform was added (and false if not)
and added the same logic to "removePlatform()"

and "typos" is my middle name :) I'll try and spot them if I can :)

thanks for all the reports! helps a lot!

**Comment by davidp57** [comment]
You're welcome, thanks for your script.
I've integrated it in my VEAF library now (https://github.com/VEAF/VEAF-Mission-Creation-Tools/blob/master/src/scripts/veaf/veafHoundElintHelper.lua)

**Comment by uriba107** [comment]
Implemented in 0.1.1
