### ISSUE TITLE
Add typical MPA to DB

### ISSUE THREAD

**Issue by Dicio83** [uriba107/DCS-Hound#48]
Would be usefull to add units from "Military Aircraft Mod" to the DB - e.g.: P3C Orion and P8A. They have in reallife the capability to locate radar transmitters

**Comment by uriba107** [comment]
will defiantly do that whenever I can as my DCS PC is down right now :(

I assume this is the P-3
https://www.digitalcombatsimulator.com/en/files/3307071/

and this is the P-8?
https://www.digitalcombatsimulator.com/en/files/3321581/

if there are any others please LMK.

I will try and provide a snippet to add to the DB for you to test just in case (even if I can't test it)

**Comment by Dicio83** [comment]
Yes that are the units.

Thank you!

**Comment by uriba107** [comment]
Added P-8 for 0.3.4. 
still working on P-3

**Comment by uriba107** [comment]
P-3C added for 0.3.4

**Comment by Dicio83** [comment]
Nice. Thank you!

**Comment by uriba107** [comment]
implemented in latest development build

**Comment by Dicio83** [comment]
Thank you so much for your work!
