### ISSUE TITLE
Tu-204/214 ELINT

### ISSUE THREAD

**Issue by SteelersForever** [uriba107/DCS-Hound#49]
**Is your feature request related to a problem? Please describe.**
I always wanted a Tu-204/214 ELINT platform. However, you haven't put it in the Hound ELINT script.

**Describe the solution you'd like**
Can you please add the Tu-204/214 to the Hound ELINT? The link to the Tu-204/214 mod is below:

https://www.digitalcombatsimulator.com/en/files/3327489/

**Describe alternatives you've considered**
I cannot really think of any alternatives other than just adding the Tu-204/214 and it seems a bit lacking to not have that aircraft.

**Additional context**
https://www.digitalcombatsimulator.com/en/files/3327489/ is the link to the Tu-204/214 mod.

I am so, so, so sorry for commenting on another repo. But I am new and didn't have a clue how to open the issue on Hound's repo. Now I know. Thanks for telling me!

**Comment by uriba107** [comment]
Added for 0.3.4

**Comment by uriba107** [comment]
implemented in latest development build
