### ISSUE TITLE
:systemOn calls :systemOff, displaying messages that lead to user confusion

### ISSUE THREAD

**Issue by davidp57** [uriba107/DCS-Hound#5]
https://github.com/uriba107/DCS-Hound/blob/1f7dc01b48bbbce596016efbf87a8b907be3cf0f/src/05%20-%20HoundElint.lua#L494

Could be better to move the actual code out of HoundElint:systemOff(), into a private function that could be called both in HoundElint:systemOff() and HoundElint:systemOn().
Only HoundElint:systemOff() would output the "Hound ELINT system is now Offline" message

**Comment by uriba107** [comment]
both systemOn and systemOff now receive and optional "notify" variable. if nil or true the text message will be shown. 
systemOn will call systemOff with false internally to avoid confusion.

thanks! :)

**Comment by uriba107** [comment]
Fixed in 0.1.1
