### ISSUE TITLE
CJS Superbug Mod

### ISSUE THREAD

**Issue by SteelersForever** [uriba107/DCS-Hound#50]
**Is your feature request related to a problem? Please describe.**
At the moment, the CJS Superbug mod no longer replaces the stock F/A-18C. However, you have not added the EA-18G to the Hound ELINT script.

**Describe the solution you'd like**
So, you can make the ELINT-capable EA-18G (It is capable of ELINT) without making the F/A-18C ELINT-capable (It isn't)

**Describe alternatives you've considered**
I have used other aircraft, but at the moment we do not have any carrier-borne fighters with ELINT capabilities. The EA-18G could fix that problem.

**Additional context**
Maybe you could do the same thing for the VSN F-35, which is ELINT-capable.

**Comment by uriba107** [comment]
Duplicates #40.

**Comment by uriba107** [comment]
implemented in latest development build
