### ISSUE TITLE
Fix getcategory DCS 2.9.1.48111

### ISSUE THREAD

**Issue by sevenfifty777** [uriba107/DCS-Hound#55]
Hi 
Since last DCS 2.9 it was a change to getCategory calls for Object.getCategory()

i got some error when adding some platform (in my case was some C17)

not sure if you are already working on it, and i am not familiar with pull request
i made change in the last HoundElint-3.4.lua where i modified all getcategory calls to Object.getCategory()
i have tested it and i don't get any more issue in logs regarding adding some platform 

[HoundElint-3.4.zip](https://github.com/uriba107/DCS-Hound/files/13467931/HoundElint-3.4.zip)

**Comment by uriba107** [comment]
Thanks you for reporting.! 
It was already fixed internally. But I had not had a chance to publish the patched version.
Thanks you very much!
